# Configuracion del servidor
server.port=${SERVER_PORT}
spring.application.name=usuarios
#logging.level.com.arka.microservice.usuarios=INFO
# Nivel de log para las peticiones http y excepciones
logging.level.org.springframework.web=DEBUG
# Habilita el logging para tus clases (ejemplo, si usas package com.arka.microservice)
logging.level.com.arka.microservice=DEBUG

# Configuracion de la conexion R2DBC
adapters.r2dbc.host=${DB_HOST}
adapters.r2dbc.port=${DB_PORT}
adapters.r2dbc.database=${DB_NAME}
adapters.r2dbc.schema=${DB_SCHEMA}
adapters.r2dbc.username=${DB_USERNAME}
adapters.r2dbc.password=${DB_PASSWORD}

# Configuracion de Flyway para las migraciones de base de datos
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}
spring.flyway.user=${adapters.r2dbc.username}
spring.flyway.password=${adapters.r2dbc.password}
spring.flyway.schemas=${adapters.r2dbc.schema}
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Configuración R2DBC - Usando solo la URL sin propiedades de pool
spring.r2dbc.url=r2dbc:postgresql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}?schema=${adapters.r2dbc.schema}
spring.r2dbc.username=${adapters.r2dbc.username}
spring.r2dbc.password=${adapters.r2dbc.password}

# Documentacion
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.enabled=true

# Configuracion de mensajes
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Spring Security
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.jwt.refresh-token=${JWT_REFRESH_TOKEN}